package resource;

public enum CommandName {

    //admin
    ADD_ALBUM,
    ADD_ARTIST,
    ADD_AUDIOTRACK_ALBUM,
    ADD_AUDIOTRACK_SINGLE,
    ADD_PACKAGE,
    ADD_PACKAGETRACK,
    CHANGE_CLIENT_BONUS,
    DELETE_TRACK_FROM_PACKAGE,
    GET_ALL_CLIENTS,
    GET_ALL_PURCHASES,
    SET_MONEY_TO_CLIENT,
    UPDATE_AUDIOTRACK_PRICE,
    UPDATE_PACKAGE_NAME,

    //client
    CHECK_CLIENT_BALANCE,
    GET_CLIENT_PURCHASES,
    MAKE_PURCHASE,
    SIGN_UP_CLIENT,

    //common
    CHANGE_PASSOWORD,
    GET_ALBUMS_OF_ARTIST,
    GET_ALBUM_USING_NAME,
    GET_ALL_ARTIST,
    GET_ALL_AUDIOTRACKS,
    GET_ALL_PACKAGES,
    GET_ARTIST_USING_NAME,
    GET_AUDIOTRACK_OF_ARTIST,
    GET_AUDIOTRACK_OF_PACKAGE,
    GET_AUDIOTRACK_USING_NAME,
    SIGN_IN
}
