INSERT INTO purchase (TotalPrice, Status, IdUser) VALUES (12, 'COMPLETED', 1);
INSERT INTO purchase (TotalPrice, Status, IdUser, Date) VALUES (23, 'COMPLETED', 3, '2015-12-12');
INSERT INTO purchase (TotalPrice, Status, IdUser) VALUES (12, 'COMPLETED', 2);
INSERT INTO purchase (TotalPrice, Status, IdUser, Date) VALUES (24, 'COMPLETED', 4, '2000-01-01');
INSERT INTO purchase (TotalPrice, Status, IdUser) VALUES (54, 'COMPLETED', 2);
INSERT INTO purchase (TotalPrice, Status, IdUser) VALUES (1, 'COMPLETED', 3);
INSERT INTO purchase (TotalPrice, Status, IdUser) VALUES (5, 'COMPLETED', 6);
INSERT INTO purchase (TotalPrice, Status, IdUser) VALUES (6, 'COMPLETED', 11);
INSERT INTO purchase (TotalPrice, Status, IdUser) VALUES (9, 'REJECTED', 12);
INSERT INTO purchase (TotalPrice, Status, IdUser) VALUES (11, 'REJECTED', 15);
INSERT INTO purchase (TotalPrice, Status, IdUser) VALUES (13, 'REJECTED', 14);
INSERT INTO purchase (TotalPrice, Status, IdUser) VALUES (21, 'SUBMITTED', 8);
INSERT INTO purchase (TotalPrice, Status, IdUser) VALUES (13, 'SUBMITTED', 9);
